name: Pull Request Tests

on:
  merge_group:
  pull_request:
    paths-ignore:
      # The ignore only works only if changes to the main branch only include the following files.
      # So if the commit only contain .md changes but the PR change contain more, the ignore fails
      # https://github.com/actions/runner/issues/2324#issuecomment-1703345084
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '**.png'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

permissions: read-all

jobs:
  pre-commit-lint-security:
    runs-on: ubuntu-24.04-arm
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - name: Install pre-commit
        run: |
          pip3 install pre-commit

      - run: corepack enable

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: abatilo/actions-poetry@v4

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.88.29
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Install dependencies
        run: |
          make install-all
      - name: Lint and code formatting
        run: |
          make check-all

  test-iac:
    runs-on: ubuntu-24.04-arm
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: abatilo/actions-poetry@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - run: corepack enable
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: make test
#  test-app:
#    runs-on: ubuntu-24.04-arm
#    if: ${{ !github.event.pull_request.draft }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - uses: actions/setup-python@v5
#        with:
#          python-version: 3.13
#      - uses: abatilo/actions-poetry@v4
#
#      - name: Install dependencies
#        working-directory: ./app
#        run: |
#          make install
#
#      - name: Test
#        working-directory: ./app
#        run: |
#          make test
